"""adds users table

Revision ID: 689742d1deec
Revises: 0c11f8d15a60
Create Date: 2024-06-04 13:50:41.822952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689742d1deec'
down_revision = '0c11f8d15a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
